#region License
// --------------------------------------------------------------------------------------------------------------------
// <copyright file="MongoSimpleTypes.cs" company="The original author or authors.">
//   Copyright 2002-2013 the original author or authors.
//   
//   Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
//   the License. You may obtain a copy of the License at
//   
//   http://www.apache.org/licenses/LICENSE-2.0
//   
//   Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
//   an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
//   specific language governing permissions and limitations under the License.
// </copyright>
// --------------------------------------------------------------------------------------------------------------------
#endregion

using System;
using System.Linq;
using System.Numerics;
using System.Text;
using System.Text.RegularExpressions;
using MongoDB.Bson;
using Spring.Collections.Generic;
using Spring.Data.Mapping.Model;
using MongoDB.Driver;

namespace Spring.Data.MongoDb.Core.Mapping
{
    /// <summary>
    /// Simple constant holder for a <see cref="SimpleTypeHolder"/> enriched with Mongo specific simple types.
    /// </summary>
    /// <author>Oliver Gierke</author>
    /// <author>Thomas Trageser</author>
    public static class MongoSimpleTypes
    {
        private static readonly ISet<Type> MONGO_SIMPLE_TYPES = new HashedSet<Type>()
            {
                typeof (MongoDBRef),
                typeof (ObjectId),
                typeof (BsonDocument),
                typeof (Regex),
                typeof (BsonBinaryData),
                typeof (Guid)
            };

        public static readonly ISet<Type> AUTOGENERATED_ID_TYPES = new HashedSet<Type>()
            {
                typeof (ObjectId),
                typeof (string),
                typeof (BigInteger)
            };
	    public static readonly SimpleTypeHolder HOLDER = new SimpleTypeHolder(MONGO_SIMPLE_TYPES, true);
    }
}
