using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: CLSCompliantAttribute(true)]
[assembly: ComVisibleAttribute(false)]
[assembly: AssemblyProductAttribute("Spring.NET Data MongoDb 1.0.0 (alpha) for .NET 4.0")]
[assembly: AssemblyCompanyAttribute("http://www.springframework.net/")]
[assembly: AssemblyCopyrightAttribute("Copyright 2012 SpringSource")]
[assembly: AssemblyTrademarkAttribute("Apache License, Version 2.0")]
[assembly: AssemblyCultureAttribute("")]
[assembly: AssemblyVersionAttribute("1.0.0.2000")]
[assembly: AssemblyConfigurationAttribute("net-4.0; 1.0.0.2000; dev")]

